### ISSUE TITLE
Yahoo API is broken, won't suggest any ticker

### ISSUE THREAD

**Issue by anddam** [premnirmal/TodayStocks#1]
The program isn't able to add new ticker, the issue is likely a change in the Yahoo Finance API.
You can make current requests to d.yimg.com work by adding 'region' and 'lang' HTTP parameters (any value will do, even empty string) but the API now returns only one result per query.

Seems the Android version has switched to markitondemand.com API, maybe the iOS version should as well.

If you're going to build with iOS 9 target you'll need to add exceptions to Info.plist for App Transport Security in order to use non-SSL URIs.

**Comment by anddam** [comment]
Any update?

**Comment by premnirmal** [comment]
Sorry for the delay. Fixed here: https://github.com/premnirmal/TodayStocks/commit/e35710c29c9d138fd6dc0a35067cabf4ca9d8871

Will submit an update to the app store this weekend

**Comment by premnirmal** [comment]
new version submitted, waiting for review

**Comment by anddam** [comment]
Thanks.
